# Generated by Django 5.2 on 2025-05-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agency_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
